server:
  port: 9090

directors:
  chunk:
    size: 20
  source:
    file: data/directors.csv
  template:
    file: movie_report.ftl

tmdb:
  base-url: https://api.themoviedb.org/3
  api-key: ${TMDB_API_KEY}
  account-id: ${TMDB_ACCOUNT_ID}
  parameters:
    language: "en-US"

spring:
  application:
    name: "Director List"
  banner:
    location: banner.txt
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9091/directors_db?autosave=always&reWriteBatchedInserts=true
    username: directors_user
    password: superpassword
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    cache: false  # Set to true in production
    charset: UTF-8
    content-type: text/html
    settings:
      number_format: "0.##"
      date_format: "yyyy-MM-dd"
      time_format: "HH:mm:ss"
      datetime_format: "yyyy-MM-dd HH:mm:ss"
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
    default-schema: director_schema
  task:
    scheduling:
      pool:
        size: 100
      thread-name-prefix: "schedule-tasks-"

logging:
  level:
    root: INFO
    pt.pauloortolan.directors: DEBUG
    org.springframework.web: INFO
    org.springframework.web.servlet.view.freemarker: DEBUG
  file:
    path: logs
    name: logs/directors.log
